-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 15:25:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wildmercato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wildmercato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildmercato` DEFAULT CHARACTER SET utf8 ;
USE `wildmercato` ;

-- -----------------------------------------------------
-- Table `wildmercato`.`championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildmercato`.`championship` (
  `idchampionship` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NOT NULL,
  `logo` VARCHAR(500) NULL,
  PRIMARY KEY (`idchampionship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildmercato`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildmercato`.`team` (
  `idteam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `championshipId` INT NOT NULL,
  `fanion` VARCHAR(2500) NULL,
  `stadium` VARCHAR(500) NULL,
  `stadium_pic` VARCHAR(500) NULL,
  PRIMARY KEY (`idteam`),
  INDEX `fk_championship_idx` (`championshipId` ASC) VISIBLE,
  CONSTRAINT `fk_championship`
    FOREIGN KEY (`championshipId`)
    REFERENCES `wildmercato`.`championship` (`idchampionship`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildmercato`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildmercato`.`player` (
  `idplayer` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(125) NOT NULL,
  `firstname` VARCHAR(125) NOT NULL,
  `team_idteam` INT NOT NULL,
  `picture` VARCHAR(2400) NULL,
  PRIMARY KEY (`idplayer`, `team_idteam`),
  INDEX `fk_player_team1_idx` (`team_idteam` ASC) VISIBLE,
  CONSTRAINT `fk_player_team1`
    FOREIGN KEY (`team_idteam`)
    REFERENCES `wildmercato`.`team` (`idteam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildmercato`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildmercato`.`transfer` (
  `player_idplayer` INT NOT NULL,
  `oldTeam` INT NOT NULL,
  `newTeam` INT NOT NULL,
  PRIMARY KEY (`player_idplayer`, `oldTeam`, `newTeam`),
  INDEX `fk_newTeam_plaer_idx` (`newTeam` ASC) VISIBLE,
  INDEX `fk_oldTeam_player_idx` (`oldTeam` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_player`
    FOREIGN KEY (`player_idplayer`)
    REFERENCES `wildmercato`.`player` (`idplayer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_newTeam_player`
    FOREIGN KEY (`newTeam`)
    REFERENCES `wildmercato`.`team` (`idteam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oldTeam_player`
    FOREIGN KEY (`oldTeam`)
    REFERENCES `wildmercato`.`team` (`idteam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wildmercato`.`championship`
-- -----------------------------------------------------
START TRANSACTION;
USE `wildmercato`;
INSERT INTO `wildmercato`.`championship` (`idchampionship`, `name`, `logo`) VALUES (1, 'Ligue 1', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wildmercato`.`team`
-- -----------------------------------------------------
START TRANSACTION;
USE `wildmercato`;
INSERT INTO `wildmercato`.`team` (`idteam`, `name`, `city`, `championshipId`, `fanion`, `stadium`, `stadium_pic`) VALUES (1, 'Paris Saint-Germain', 'Paris', 1, NULL, NULL, NULL);
INSERT INTO `wildmercato`.`team` (`idteam`, `name`, `city`, `championshipId`, `fanion`, `stadium`, `stadium_pic`) VALUES (2, 'FC Nantes', 'Nantes', 1, NULL, NULL, NULL);
INSERT INTO `wildmercato`.`team` (`idteam`, `name`, `city`, `championshipId`, `fanion`, `stadium`, `stadium_pic`) VALUES (3, 'Olympique Lyonnais', 'Lyon', 1, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wildmercato`.`player`
-- -----------------------------------------------------
START TRANSACTION;
USE `wildmercato`;
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (1, 'Mbappe', 'Kylian', 1, NULL);
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (2, 'Verratti', 'Marco', 1, NULL);
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (3, 'Delort', 'Andy', 2, NULL);
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (4, 'Blas', 'Ludovic', 2, NULL);
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (5, 'Lacazette', 'Alexandre', 3, NULL);
INSERT INTO `wildmercato`.`player` (`idplayer`, `lastname`, `firstname`, `team_idteam`, `picture`) VALUES (6, 'Tolisso', 'Corentin', 3, NULL);

COMMIT;

